CREATE TABLE IF NOT EXISTS media (
  id INT AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255) NOT NULL UNIQUE,
  original_name VARCHAR(255) DEFAULT NULL,
  path VARCHAR(500) NOT NULL,
  size INT NOT NULL DEFAULT 0,
  width INT DEFAULT NULL,
  height INT DEFAULT NULL,
  mime VARCHAR(60) DEFAULT 'image/webp',
  uploaded_by INT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT NULL,
  INDEX idx_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
