-- Ek varsayılan sayfalar (footer için)
INSERT INTO pages (slug,title,content) VALUES
  ('kargo-teslimat','Kargo & Teslimat',
   '<h2>Kargo & Teslimat</h2><p>Siparişleriniz onayın ardından <strong>1-3 iş günü</strong> içinde anlaşmalı kargo firmamızla gönderilir.</p><h3>Kargo Süreleri</h3><ul><li>Büyükşehirler: 1-2 iş günü</li><li>Diğer iller: 2-4 iş günü</li><li>Köy/uzak bölgeler: 3-5 iş günü</li></ul><h3>Kargo Ücreti</h3><p>Yurt içi tüm siparişlerde <strong>kargo ücretsizdir</strong>.</p><h3>Sipariş Takibi</h3><p>Siparişiniz kargoya verildiğinde e-posta ile takip numarası iletilir. Hesabım sayfasından da takibinizi yapabilirsiniz.</p>'),
  ('iade-degisim','İade & Değişim',
   '<h2>İade & Değişim Politikası</h2><p>Müşteri memnuniyeti önceliğimizdir. Ürünlerinizi <strong>14 gün</strong> içinde iade edebilir veya değiştirebilirsiniz.</p><h3>İade Koşulları</h3><ul><li>Ürün kullanılmamış ve orijinal ambalajında olmalı</li><li>Fatura ile birlikte gönderilmeli</li><li>Hijyenik özellik taşıyan ürünler iade edilemez</li></ul><h3>Nasıl İade Ederim?</h3><ol><li>İletişim sayfasından bize ulaşın</li><li>İade onayı sonrası anlaşmalı kargoyla ücretsiz gönderim</li><li>Ürün tarafımıza ulaştığında 7 iş günü içinde iadeniz işleme alınır</li></ol><h3>Para İadesi</h3><p>Ödemeyi yaptığınız yönteme göre 1-14 iş günü içinde iadeniz tamamlanır.</p>'),
  ('sss','Sıkça Sorulan Sorular',
   '<h2>Sıkça Sorulan Sorular</h2><h3>Siparişim ne zaman elime ulaşır?</h3><p>Onaylanan siparişler 1-3 iş günü içinde kargoya verilir; teslimat süresi bölgenize göre 1-5 iş günüdür.</p><h3>Kargo ücreti var mı?</h3><p>Yurt içi tüm siparişlerde kargo ücretsizdir.</p><h3>Hangi ödeme yöntemlerini kullanabilirim?</h3><p>Havale/EFT, kredi kartı ve kapıda ödeme seçeneklerimiz mevcuttur.</p><h3>Ürünü iade edebilir miyim?</h3><p>Evet, 14 gün içinde koşulsuz iade hakkınız vardır. Detaylar için <a href="page.php?slug=iade-degisim">İade &amp; Değişim</a> sayfasına bakabilirsiniz.</p><h3>Üye olmadan sipariş verebilir miyim?</h3><p>Evet, misafir olarak da sipariş verebilirsiniz; ancak üyelik daha hızlı ödeme ve sipariş takibi sağlar.</p><h3>Faturamı nasıl alırım?</h3><p>E-fatura/e-arşiv kayıtlı e-posta adresinize otomatik gönderilir.</p><h3>Sipariş iptali yapabilir miyim?</h3><p>Henüz kargoya verilmemiş siparişler için iptal mümkündür. İletişime geçmeniz yeterlidir.</p>')
ON DUPLICATE KEY UPDATE title=VALUES(title);
